name: Generate test matrices pages

on:
  pull_request_target:
    branches:
      - main
    types: [closed]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check out'
        default: 'main'
        required: false
        type: string
      pr_number:
        description: 'PR number to process (must be specified as a number or "all")'
        required: true
        type: string
permissions:
  contents: write
jobs:
  generate-matrix:
    if: github.event_name != 'pull_request_target' || (github.repository == 'rh-ecosystem-edge/nvidia-ci' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    env:
      DASHBOARD_OUTPUT_DIR: 'workflows/test_matrix_dashboard/output'
      PREVIOUS_JSON_FILE: 'gpu_operator_matrix_old.json'
      CURRENT_JSON_FILE: 'gpu_operator_matrix.json'
      DASHBOARD_HTML_FILE: 'gpu_operator_matrix.html'
    steps:
      - name: Determine PR Number
        id: determine_pr
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request_target" ]; then
              echo "Processing merged pull request."
              echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"
          else
              echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref || github.event.inputs.branch }}

      - name: Checkout GitHub Pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ${{ env.DASHBOARD_OUTPUT_DIR }}

      - name: Back up ${{ env.DASHBOARD_OUTPUT_DIR }}/${{ env.CURRENT_JSON_FILE }}
        run: |
          cp "${{ env.DASHBOARD_OUTPUT_DIR }}/${{ env.CURRENT_JSON_FILE }}" "${{ env.DASHBOARD_OUTPUT_DIR }}/${{ env.PREVIOUS_JSON_FILE }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r workflows/dashboard_requirements.txt

      - name: Run Dashboard Generation Script
        run: |
          echo "Processing PR: ${{ steps.determine_pr.outputs.PR_NUMBER }}"
          python workflows/generate_ci_dashboard.py \
            --pr_number "${{ steps.determine_pr.outputs.PR_NUMBER }}" \
            --baseline_data_file "${{ env.CURRENT_JSON_FILE }}" \
            --merged_data_file "${{ env.CURRENT_JSON_FILE }}" \
            --dashboard_file "${{ env.DASHBOARD_HTML_FILE }}" \
            --output_dir "${{ env.DASHBOARD_OUTPUT_DIR }}"

      - name: Deploy HTML to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ${{ env.DASHBOARD_OUTPUT_DIR }}
          clean: false
          force: false
